title = "NGO “Civic Synergy”"
baseURL = "https://gohugo-theme-ananke.pages.dev"
theme = "ananke"
resourceDir = "../resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content/en"
languageCode = 'en-US'
weight = 1
title = "NGO “Civic Synergy”"
# languageDirection = 'rtl' for Right-To-Left languages

[languages.ukr]
contentDir = "content/ukr"
languageCode = 'ukr'
weight = 1
title = "ГО “Громадська синергія”"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = "/images/Logos/LOGO color.png"
site_logo = "/images/Logos/NGO color.svg"
description = ""
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-near-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3

[params.ananke.social.share]
networks = [
  "email",
  "facebook",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "facebook",
  "linkedin",
  "instagram"
]

[params.ananke.social.facebook]
username = "patrick.kollitsch"
# profilelink = "https://www.facebook.com/patrick.kollitsch"

[params.ananke.social.linkedin]
username = "patrickkollitsch"

[params.ananke.social.instagram]
username = "nagirny_roman"
# profilelink = "https://www.instagram.com/nagirny_roman"
